services:
  mysql:
    image: mysql:8.0
    container_name: stock-broker-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stock_broker
      MYSQL_USER: broker
      MYSQL_PASSWORD: brokerpass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
